### ISSUE TITLE
代理无法添加成功

### ISSUE THREAD

**Issue by NFIT-YSW** [zmzimpl/chrome-power-app#12]
![20240325153323](https://github.com/zmzimpl/chrome-power-app/assets/32082961/c3783aa1-215f-4757-a448-6deed1bd0568)

**Comment by zmzimpl** [comment]
v1.1.1 已修复本地代理和 socks5 代理导入
查看 [commit](https://github.com/zmzimpl/chrome-power-app/commit/9f544681dace6f152954ea48a68a5c239c82bd81)
