### ISSUE TITLE
多进程窗口selenium调试端口只有1个

### ISSUE THREAD

**Issue by LuisRain** [zmzimpl/chrome-power-app#15]
**Describe the bug**
新建两个窗口，API打开之后返回的调试端口port为顺序递增，比如9222，9223分别是两个窗口返回的调试port。
但是两个窗口其中webSocketDebuggerUrl 返回的地址端口却是一模一样的。
这样会导致多进程调试无法处理，因为都是用的一样的地址，且port其实也是未生效的

**To Reproduce**
1、新建多个窗口
2、使用selenium进行多个窗口同时调试访问不同的页面

**Comment by zmzimpl** [comment]
![image](https://github.com/zmzimpl/chrome-power-app/assets/27490895/69588280-d8b2-4fed-b135-1fc473f5208a)
![image](https://github.com/zmzimpl/chrome-power-app/assets/27490895/d7c003f3-483d-47b9-8a60-3a912a3108d3)
同时打开两个进程，port 怎么会是一样的的？使用这类自动化工具的时候，应该先调用接口唤起窗口，然后用 selenium 连接，页面是否相同和 port 会不会被重复利用没关系。

参考以下群友的代码：
```
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from chromedriver_py import binary_path
import requests

id = "2"
open_url = f"http://127.0.0.1:49156/profiles/browser?windowId={id}"
res = requests.get(open_url).json()
debug_port = res['window']['port']
service=Service(executable_path=binary_path)
options = webdriver.ChromeOptions()
options.add_experimental_option("debuggerAddress", f'127.0.0.1:{debug_port}')
driver = webdriver.Chrome(service=service,options=options)
driver.get('https://www.baidu.com/')
```

**Comment by LuisRain** [comment]
> ![image](https://private-user-images.githubusercontent.com/27490895/318236309-69588280-d8b2-4fed-b135-1fc473f5208a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MzQ5ODQsIm5iZiI6MTcxMTkzNDY4NCwicGF0aCI6Ii8yNzQ5MDg5NS8zMTgyMzYzMDktNjk1ODgyODAtZDhiMi00ZmVkLWIxMzUtMWZjNDczZjUyMDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAxMjQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNzYxOTdkM2IwNGEwZjdjNTViMjI1ZjlhZGQ0MGM0MmEyYjA3MTZhZTczNjAyZTQ3MzQ3Mjc3OWQ2ZWU2MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-jUoQIiazSntZjwHZvWj9fD7eahO3Wv1uPXxoJwubcU) ![image](https://private-user-images.githubusercontent.com/27490895/318236304-d7c003f3-483d-47b9-8a60-3a912a3108d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MzQ5ODQsIm5iZiI6MTcxMTkzNDY4NCwicGF0aCI6Ii8yNzQ5MDg5NS8zMTgyMzYzMDQtZDdjMDAzZjMtNDgzZC00N2I5LThhNjAtM2E5MTJhMzEwOGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAxMjQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MGM1NmJkMGRlZTg3MzA0YmNiNDc5YzFmYzZiMTMzM2RiMDE2MjM4NWU1ZDQyOTVjNzk4ZDZiN2EyNDlkZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cWa39_L9FN4xjzdgsAt17wrCZvN9yS8iGAdsz7ZkIMw) 同时打开两个进程，port 怎么会是一样的的？使用这类自动化工具的时候，应该先调用接口唤起窗口，然后用 selenium 连接，页面是否相同和 port 会不会被重复利用没关系。
> 
> 参考以下群友的代码：
> 
> ```
> from selenium import webdriver
> from selenium.webdriver.chrome.service import Service
> from chromedriver_py import binary_path
> import requests
> 
> id = "2"
> open_url = f"http://127.0.0.1:49156/profiles/browser?windowId={id}"
> res = requests.get(open_url).json()
> debug_port = res['window']['port']
> service=Service(executable_path=binary_path)
> options = webdriver.ChromeOptions()
> options.add_experimental_option("debuggerAddress", f'127.0.0.1:{debug_port}')
> driver = webdriver.Chrome(service=service,options=options)
> driver.get('https://www.baidu.com/')
> ```

群友的代码是单线程没有并发。
这边并发后port有可能会一样，有可能是顺序递增的
这是我这边多进程的代码：
```
def get_driver_with_port(port):
    options = Options()
    options.debugger_address = "127.0.0.1:" + str((port))
    chrome_driver = r"some drvicer"
    s = Service()
    s.path = chrome_driver
    driver = webdriver.Chrome(service=s, options=options)
    wait = WebDriverWait(driver, 50, 1)
    selenium_login(port)
    return driver, wait

def go(item):
    ct = requests.get("http://localhost:49156/profiles/browser?windowId=" + str(item["id"]))
    js = json.loads(ct.content)
    w_port = js["window"]["port"]
    print("调用id:{}返回的结果: {}".format(item["id"],js))
    driver, wait = get_driver_with_port(w_port)

    driver.get("http://google.com")
    time.sleep(20)


ct = requests.get("http://localhost:49156/profiles")
js = json.loads(ct.content)
threadNum = 10
pool = ThreadPool(threadNum)
pool.map(go, js)
pool.close()
pool.join()
```


然后日志如图：
<img width="853" alt="20240401093222" src="https://github.com/zmzimpl/chrome-power-app/assets/16148847/cd5fa5e7-44bf-4ed0-931c-7ebaac40e840">

**Comment by zmzimpl** [comment]
> > ![image](https://private-user-images.githubusercontent.com/27490895/318236309-69588280-d8b2-4fed-b135-1fc473f5208a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MzQ5ODQsIm5iZiI6MTcxMTkzNDY4NCwicGF0aCI6Ii8yNzQ5MDg5NS8zMTgyMzYzMDktNjk1ODgyODAtZDhiMi00ZmVkLWIxMzUtMWZjNDczZjUyMDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAxMjQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNzYxOTdkM2IwNGEwZjdjNTViMjI1ZjlhZGQ0MGM0MmEyYjA3MTZhZTczNjAyZTQ3MzQ3Mjc3OWQ2ZWU2MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-jUoQIiazSntZjwHZvWj9fD7eahO3Wv1uPXxoJwubcU) ![image](https://private-user-images.githubusercontent.com/27490895/318236304-d7c003f3-483d-47b9-8a60-3a912a3108d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MzQ5ODQsIm5iZiI6MTcxMTkzNDY4NCwicGF0aCI6Ii8yNzQ5MDg5NS8zMTgyMzYzMDQtZDdjMDAzZjMtNDgzZC00N2I5LThhNjAtM2E5MTJhMzEwOGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAxMjQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MGM1NmJkMGRlZTg3MzA0YmNiNDc5YzFmYzZiMTMzM2RiMDE2MjM4NWU1ZDQyOTVjNzk4ZDZiN2EyNDlkZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cWa39_L9FN4xjzdgsAt17wrCZvN9yS8iGAdsz7ZkIMw) 同时打开两个进程，port 怎么会是一样的的？使用这类自动化工具的时候，应该先调用接口唤起窗口，然后用 selenium 连接，页面是否相同和 port 会不会被重复利用没关系。
> > 参考以下群友的代码：
> > ```
> > from selenium import webdriver
> > from selenium.webdriver.chrome.service import Service
> > from chromedriver_py import binary_path
> > import requests
> > 
> > id = "2"
> > open_url = f"http://127.0.0.1:49156/profiles/browser?windowId={id}"
> > res = requests.get(open_url).json()
> > debug_port = res['window']['port']
> > service=Service(executable_path=binary_path)
> > options = webdriver.ChromeOptions()
> > options.add_experimental_option("debuggerAddress", f'127.0.0.1:{debug_port}')
> > driver = webdriver.Chrome(service=service,options=options)
> > driver.get('https://www.baidu.com/')
> > ```
> 
> 群友的代码是单线程没有并发。 这边并发后port有可能会一样，有可能是顺序递增的。 然后你的意思实现该功能是：如果要多个窗口同时操作，就顺序打开10个窗口，然后再并发去driver连接？ 这个我也试了，单线程顺序打开也会端口一致 这是我这边多进程的代码：
> 
> ```
> def get_driver_with_port(port):
> 
>     return driver, wait
> 
> def go(item):
>     ct = requests.get("http://localhost:49156/profiles/browser?windowId=" + str(item["id"]))
>     js = json.loads(ct.content)
>     w_port = js["window"]["port"]
>     print("调用id:{}返回的结果: {}".format(item["id"],js))
>     driver, wait = get_driver_with_port(w_port)
> 
>     driver.get("http://google.com")
>     time.sleep(20)
> 
> 
> ct = requests.get("http://localhost:49156/profiles")
> js = json.loads(ct.content)
> threadNum = 10
> pool = ThreadPool(threadNum)
> pool.map(go, js)
> pool.close()
> pool.join()
> ```
> 
> 然后日志如图： <img alt="20240401093222" width="853" src="https://private-user-images.githubusercontent.com/16148847/318315827-cd5fa5e7-44bf-4ed0-931c-7ebaac40e840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MDA0NzMsIm5iZiI6MTcxMzYwMDE3MywicGF0aCI6Ii8xNjE0ODg0Ny8zMTgzMTU4MjctY2Q1ZmE1ZTctNDRiZi00ZWQwLTkzMWMtN2ViYWFjNDBlODQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA4MDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMjM0OTU5YjhlOGJlN2U1MjM5YTA3NmFkZjBmMjQ0MTUzMjU1N2Q0YTc2NGIxZDZlZTgyZTMwYTU3NGI4ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jOAxmavGTiRicE0IEeRMnPfLAsMlvYXeAlZeVgdCjZU">

增加了锁，应该可以了
