### ISSUE TITLE
安装好以后为啥打不开

### ISSUE THREAD

**Issue by heiniao998** [zmzimpl/chrome-power-app#16]
安装好以后为啥打不开。界面跳不出来 ，闪退

**Comment by changmingjin** [comment]
我也是，你找到解决办法了吗？

**Comment by zmzimpl** [comment]
用的是什么系统？需要管理员权限，有没有给

**Comment by changmingjin** [comment]
> 使用的是什么系统？需要管理员权限，有没有给

Windows 2019 DataCenter 64位中文版2022(40GB)
的系统，我是右键管理员打开安装程序的，后续还需要额外管理员权限？不太懂怎么设置，本地电脑安装成功了，但是云服务器这个电脑【Windows 2019 DataCenter 64位中文版2022(40GB)】安装了之后打开闪退了

**Comment by changmingjin** [comment]
> > 使用的是什么系统？需要管理员权限，有没有给
> 
> Windows 2019 DataCenter 64位中文版2022(40GB) 的系统，我是右键管理员打开安装程序的，后续还需要额外管理员权限？不太懂怎么设置，本地电脑安装成功了，但是云服务器这个电脑【Windows 2019 DataCenter 64位中文版2022(40GB)】安装了之后打开闪退了

下面是程序错误的情况：
错误应用程序名称: chrome-power.exe，版本: 1.1.0.0，时间戳: 0x651cb3d9
错误模块名称: chrome-power.exe，版本: 1.1.0.0，时间戳: 0x651cb3d9
异常代码: 0x80000003
错误偏移量: 0x0000000001b8193c
错误进程 ID: 0x280
错误应用程序启动时间: 0x01da8bcd04fad030
错误应用程序路径: C:\Users\Administrator\AppData\Local\Programs\chrome-power\chrome-power.exe
错误模块路径: C:\Users\Administrator\AppData\Local\Programs\chrome-power\chrome-power.exe
报告 ID: b747ac5f-ee2d-4079-9e7e-090c4ee9f91f
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by heiniao998** [comment]
> 我也是，你找到解决办法了吗？

我的还是这样 就看不到界面，图标在任务栏亮一下 就闪退了

**Comment by heiniao998** [comment]
> Own
版本	Windows 10 专业版
操作系统内部版本	19045.4046
我是本地安装也闪退

**Comment by changmingjin** [comment]
我的本地可以，但是云服务器上的系统不行，就很奇怪，除了EXE还有其他安装方式吗？能打开的

**Comment by changmingjin** [comment]
@zmzimpl

**Comment by zmzimpl** [comment]
> > 使用的是什么系统？需要管理员权限，有没有给
> 
> Windows 2019 DataCenter 64位中文版2022(40GB) 的系统，我是右键管理员打开安装程序的，后续还需要额外管理员权限？不太懂怎么设置，本地电脑安装成功了，但是云服务器这个电脑【Windows 2019 DataCenter 64位中文版2022(40GB)】安装了之后打开闪退了

云服务我没有测试环境，无法调试，请尝试在服务器中运行源代码，看下能不能通过代码跑起来，如果能跑起来，说明需要调整一下 `.electron-builder.config.js` 配置，跑不起来，再看看具体问题。欢迎 pr

**Comment by zmzimpl** [comment]
> > Own
> > 版本	Windows 10 专业版
> > 操作系统内部版本	19045.4046
> > 我是本地安装也闪退

Win10 闪退的情况我在本地无法复现，建议运行源代码，看下是否能够跑起来

**Comment by zmzimpl** [comment]
闪退问题我今天找机器测试了一下，尝试一下在启动时配置下 --in-process-gpu 或者 --no-sandbox
<img width="341" alt="51874843202c335118147c7689df5a2" src="https://github.com/zmzimpl/chrome-power-app/assets/27490895/94a88881-8c3e-4198-a7c0-b34b77f4c952">
@changmingjin @heiniao998

**Comment by silverjie1** [comment]
> 我今天找了一个机器测试，尝试了一下在启动时配置 --in-process-gpu 或者 --no-sandbox <img alt="51874843202c335118147c7689df5a2" width="341" src="https://private-user-images.githubusercontent.com/27490895/325900137-94a88881-8c3e-4198-a7c0-b34b77f4c952.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzM2OTYsIm5iZiI6MTcxODczMzM5NiwicGF0aCI6Ii8yNzQ5MDg5NS8zMjU5MDAxMzctOTRhODg4ODEtOGMzZS00MTk4LWE3YzAtYjM0Yjc3ZjRjOTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDE3NTYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZDkxZDlmODRiMjczYzczMmZiZDQxMDhiMDRlNjhiZDJkNWYxYzA3YWY2ZjVjZmM1MTY5NjJkMWUxMDg3MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oIZotRCpVeCZP5vWtaADc_xA6lTRjK_LFgWCfx1sXrw"> @changmingjin @heiniao998
感谢，同样遇到闪退，通过这个操作解决了
