### ISSUE TITLE
代理用户名包含下划线 "_" 无法识别

### ISSUE THREAD

**Issue by zuoban** [zmzimpl/chrome-power-app#19]
**Describe the bug**
代理用户名包含下划线 "_" 无法识别
**To Reproduce**

1. 新建代理
2. 输入 `127.0.0.1:1080:t_1:pwd`

**Expected behavior**
代理正确添加
**Screenshots**

![CleanShot 2024-04-18 at 18 47 59@2x](https://github.com/zmzimpl/chrome-power-app/assets/17957457/45206fb0-b62c-4a8c-bd1c-83a4d4795c23)

**Comment by zmzimpl** [comment]
最新版已修复
