### ISSUE TITLE
打不开环境

### ISSUE THREAD

**Issue by 0xuhe** [zmzimpl/chrome-power-app#20]
**Describe the bug**
Win10 企业版LTSC

**Screenshots**
<img width="731" alt="image" src="https://github.com/zmzimpl/chrome-power-app/assets/6814715/810103ff-b34e-4ea5-a453-5fd4c75c54e0">

**Comment by zmzimpl** [comment]
本地编译运行么？看起来是获取本地的 chrome 路径出错了

**Comment by 0xuhe** [comment]
如何设置路径, 我设置里面设置了路径, 切换标签后, 发现路径栏又空了, 没有保存下来

**Comment by zmzimpl** [comment]
> 如何设置路径, 我设置里面设置了路径, 切换标签后, 发现路径栏又空了, 没有保存下来

你忘记点设置里面地下的保存了吧

**Comment by 0xuhe** [comment]
![Jietu20240601-183510@2x](https://github.com/zmzimpl/chrome-power-app/assets/6814715/616e1772-605e-439d-b34c-5b869942e17f)
没看到保存按钮
