### ISSUE TITLE
修改浏览器指纹信息

### ISSUE THREAD

**Issue by zhaotoday** [zmzimpl/chrome-power-app#3]
**Is your feature request related to a problem? Please describe.**
通过 Puppeteer 并不能修改所有的浏览器指纹信息，是否需要通过修改浏览器内核来实现？

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zmzimpl** [comment]
已经改成了内核实现，目前支持 Canvas, Audio, Webgl, UA 的修改

**Comment by zhaotoday** [comment]
我看代码是打开本地的 Chrome 浏览器，并不是打开修改内核后的 Chrome 浏览器？

**Comment by zmzimpl** [comment]
> 我看代码是打开本地的 Chrome 浏览器，并不是打开修改内核后的 Chrome 浏览器？

第一版确实是用的本地 Chrome, 目前已经是用修改编译后的 Chrome 内核，在代码根目录有一个 Chrome-bin，在打包时会处理，实际上运行就是用这个

**Comment by zhaotoday** [comment]
我看下，谢谢啦。
