### ISSUE TITLE
如何定制 Chromium 内核

### ISSUE THREAD

**Issue by zhaotoday** [zmzimpl/chrome-power-app#4]
**Is your feature request related to a problem? Please describe.**
可否出个定制 Chromium 内核的教程？

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zmzimpl** [comment]
Chromium 内核定制网上有挺多的教程，我目前暂时没有时间写这一块的

**Comment by zhaotoday** [comment]
好的，谢谢。
