### ISSUE TITLE
Business cooperation, would it be convenient for you to leave home

### ISSUE THREAD

**Issue by EchoAGI** [zmzimpl/chrome-power-app#5]
Business cooperation, would it be convenient for you to leave home

**Comment by zmzimpl** [comment]
What do you mean, "leave home"?

如果你是国人，可以直接中文交流

**Comment by EchoAGI** [comment]
Sorry. 那是AI自动发的信息. 我们需要一个定制的指纹浏览器，结合AI copilot. 有兴趣可以合作

**Comment by zmzimpl** [comment]
> Sorry. 那是AI自动发的信息. 我们需要一个定制的指纹浏览器，结合AI copilot. 有兴趣可以合作

麻烦将你们的功能需求发送到我的邮箱（zmzimpl@gmail.com），我看下能不能做再回复你

**Comment by zmzimpl** [comment]
> Sorry. 那是AI自动发的信息. 我们需要一个定制的指纹浏览器，结合AI copilot. 有兴趣可以合作

因为先前的回复带了邮箱导致最近垃圾邮件剧增，所以删了
