### ISSUE TITLE
指纹环境啥时候可以支持Puppeteer一类的控制呢

### ISSUE THREAD

**Issue by 1290799223** [zmzimpl/chrome-power-app#7]
指纹环境啥时候可以支持Puppeteer一类的控制呢
谢谢大佬！！！

**Comment by zmzimpl** [comment]
支持 Puppeteer 接入倒不是很难，把 ws 连接通过接口暴露出来就可以了，我把它一块列到近期的开发安排里面吧

**Comment by zhaotoday** [comment]
说的是同步操作功能吗？

**Comment by zmzimpl** [comment]
> 指纹环境啥时候可以支持Puppeteer一类的控制呢 谢谢大佬！！！

最新代码已经支持

**Comment by zmzimpl** [comment]
> 说的是同步操作功能吗？

不是，是提供给 Puppeteer 之类的自动化工具的一个对接接口
