### ISSUE TITLE
安装包安装后，创建环境打不开。

### ISSUE THREAD

**Issue by incity** [zmzimpl/chrome-power-app#8]
![694d8e71b69fe4f8b660ecb6680562f](https://github.com/zmzimpl/chrome-power-app/assets/7846605/9f1849a5-956b-44fa-81a5-890090d3b234)

**Comment by zhaotoday** [comment]
@incity 应该是 Chromium 内核解压失败，要手动去解压。

**Comment by zmzimpl** [comment]
看一下运行日志，确实应该是 Chromium 内核解压失败
